name: Deploy React App to EC2 via Docker Compose

on:
  push:
    branches:
      - feature/build
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: front-end/

      - name: Build React app
        run: npm run build
        working-directory: front-end/

      # EC2에서 기존 dist 삭제
      - name: Clean dist on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            rm -rf ~/ground-hub/frontend/frontend_build/OVERLAB_FE-feature-build/front-end/dist

      - name: Upload files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "front-end/dist"
          target: "~/ground-hub/frontend/front-end/dist"  # 배포 위치 (원하는 경로로 변경 가능)

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/ground-hub/docker
            docker-compose -f docker-compose.yml down frontend || true
            docker-compose -f docker-compose.yml build frontend
            docker-compose -f docker-compose.yml up frontend
